kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysqldata
  namespace: blog
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path # 指定使用存储类
  resources:
    requests:
      storage: 5Gi
